# Starter pipeline
- master

pool:
  vmImage: ubuntu-latest

steps:
- script:  npm install -g newman
           npm install -g newman-reporter-htmlextra
  displayName: 'Install newman dependencies'

- script:  newman run bfree-core.json -e core-environment.json
  displayName: 'Run api Test'
